all:
	g++ Main.cpp --std=c++1y -Wall -Wextra -g -o reviews -lboost_serialization -lboost_serialization-mt

clang:
	clang++ Main.cpp -stdlib=libc++ --std=c++1y -Wall -Wextra -g -o reviews -lboost_serialization -lboost_serialization-mt
